apiVersion: v1
kind: ReplicationController
metadata:
  name: auth-service
  labels:
    name: auth-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: auth-service
    spec:
      containers:
      - name: auth-service
        image: inforian/auth-service:
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:

