# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-editable, to be generated by system itself.', unique=True, verbose_name='Resource token')),
                ('source', models.CharField(help_text='Who wants to access something ?', max_length=255, verbose_name='Source (Requester)')),
                ('target', models.CharField(help_text='Whom Source wants to access ?', max_length=255, verbose_name='Target')),
                ('create', models.BooleanField(default=False, verbose_name='can create')),
                ('update', models.BooleanField(default=False, verbose_name='can update')),
                ('read', models.BooleanField(default=False, verbose_name='can read')),
                ('delete', models.BooleanField(default=False, verbose_name='can delete')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Non-editable, to be generated by system itself.', verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Non-editable, to be generated by system itself.', verbose_name='modified at')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Authorization',
                'verbose_name_plural': 'Authorization',
            },
        ),
    ]
