# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 07:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="Who wants to access something ? Source must match with Regular Expression ^[a-z_-]+:[0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$ , Sample Source ['organization:2db95648-b5ea-458a-9f07-a9ef51bbca21', 'organization-member:2db95648-b5ea-458a-9f07-a9ef51bbca21', 'organization_member:2db95648-b5ea-458a-9f07-a9ef51bbca21']", max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-z_-]+:[0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$')], verbose_name='Source (Who ?)')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'Authorization Policy',
                'verbose_name_plural': 'Authorization Policies',
            },
        ),
        migrations.CreateModel(
            name='AuthPolicyPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(help_text="What can be accessed ? Resource must match with Regular Expression ^vrn:resource:[a-z_-]+:([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12})?$ , Sample Resource ['vrn:resource:organization:', 'vrn:resource:organization:2db95648-b5ea-458a-9f07-a9ef51bbca21']", max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^vrn:resource:[a-z_-]+:([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12})?$')], verbose_name='Target (What ?)')),
                ('create', models.BooleanField(default=False, verbose_name='can create')),
                ('update', models.BooleanField(default=False, verbose_name='can update')),
                ('read', models.BooleanField(default=False, verbose_name='can read')),
                ('delete', models.BooleanField(default=False, verbose_name='can delete')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(db_index=True, verbose_name='modified at')),
                ('source', models.ForeignKey(help_text='Policy Source', on_delete=django.db.models.deletion.CASCADE, to='authorization.AuthPolicy')),
            ],
            options={
                'verbose_name': 'Authorization Policy Permission',
                'verbose_name_plural': 'Authorization Policy Permissions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='authpolicypermissions',
            unique_together=set([('source', 'target')]),
        ),
    ]
