# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 09:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20170426_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authpolicy',
            name='source',
            field=models.CharField(help_text="Who wants to access something ? Source must match with Regular Expression ^[a-z_-]+:[0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$ , Sample Source ['organization:2db95648-b5ea-458a-9f07-a9ef51bbca21', 'organization-member:2db95648-b5ea-458a-9f07-a9ef51bbca21', 'organization_member:2db95648-b5ea-458a-9f07-a9ef51bbca21']", max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$'), "Enter a valid source. This value may contain only match with Regular Expression ^[a-z_-]+:[0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$ , Sample Source ['organization:2db95648-b5ea-458a-9f07-a9ef51bbca21', 'organization-member:2db95648-b5ea-458a-9f07-a9ef51bbca21', 'organization_member:2db95648-b5ea-458a-9f07-a9ef51bbca21']"], verbose_name='Source (Who ?)'),
        ),
    ]
