# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20170321_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='modified_at',
            field=models.DateTimeField(db_index=True, verbose_name='modified at'),
        ),
    ]
