# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20170426_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authpolicypermissions',
            name='source',
            field=models.ForeignKey(help_text='Policy Source', on_delete=django.db.models.deletion.CASCADE, related_name='source_permission_set', to='authorization.AuthPolicy'),
        ),
    ]
