# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 10:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20170426_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authpolicy',
            name='source',
            field=models.TextField(help_text="Who wants to access something ? Source must match with Regular Expression ^[a-z_-]+:([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}):([a-z_-]+:)?([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}:)?([a-z_-]+:)?([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}:)?$ , Sample Source ['organization:2db95648-b5ea-458a-9f07-a9ef51bbca21:', 'organization-member:2db95648-b5ea-458a-9f07-a9ef51bbca21:']", unique=True, validators=[django.core.validators.RegexValidator('^[a-z_-]+:([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}):([a-z_-]+:)?([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}:)?([a-z_-]+:)?([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}:)?$', "Enter a valid Source. This value may contain only match with Regular Expression ^[a-z_-]+:([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}):([a-z_-]+:)?([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}:)?([a-z_-]+:)?([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}:)?$ , Sample Source ['organization:2db95648-b5ea-458a-9f07-a9ef51bbca21:', 'organization-member:2db95648-b5ea-458a-9f07-a9ef51bbca21:']")], verbose_name='Source (Who ?)'),
        ),
        migrations.AlterField(
            model_name='authpolicypermissions',
            name='target',
            field=models.TextField(help_text="What can be accessed ? Resource must match with Regular Expression ^^vrn:resource:[a-z_-]+:([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}:)?([a-z_-]+:)?([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}:)?([a-z_-]+:)?([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}:)?$ , Sample Resource ['vrn:resource:organization:', 'vrn:resource:organization:2db95648-b5ea-458a-9f07-a9ef51bbca21:']", validators=[django.core.validators.RegexValidator('^^vrn:resource:[a-z_-]+:([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}:)?([a-z_-]+:)?([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}:)?([a-z_-]+:)?([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}:)?$', "Enter a valid Resource. This value may contain only match with Regular Expression ^^vrn:resource:[a-z_-]+:([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}:)?([a-z_-]+:)?([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}:)?([a-z_-]+:)?([0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}:)?$ , Sample Source ['vrn:resource:organization:', 'vrn:resource:organization:2db95648-b5ea-458a-9f07-a9ef51bbca21:']")], verbose_name='Target (What ?)'),
        ),
    ]
